# Generated by Django 4.2.1 on 2023-05-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.CharField(max_length=20)),
                ('Imsak', models.TimeField()),
                ('Subuh', models.TimeField()),
                ('Terbit', models.TimeField()),
                ('Duha', models.TimeField()),
                ('Zuhur', models.TimeField()),
                ('Asar', models.TimeField()),
                ('Magrib', models.TimeField()),
                ('Isya', models.TimeField()),
            ],
            options={
                'db_table': 'jadwal',
            },
        ),
    ]
